#ifndef __ERRORS_H__
#define __ERRORS_H__

enum custom_errors {
  SUCCESS = 0,
  TYPE_ERR,
  COPY_ERR,
  ARGS_ERR,
  ARRAY_CREATE_PARAMS_ERR,
  READ_PARAMS_ERR,
  READ_OPEN_FILE_ERR,
  WRITE_ERR,
  WRITE_PARAMS_ERR,
  WRITE_OPEN_FILE_ERR,
  STREAM_READ_ERR,
  ALLOC_BUFFER_ERR,
  REALLOC_BUFFER_ERR,
  ALLOC_POS_ARRAY_ERR,
  ALLOC_POS_ARRAY_PARAMS_ERR,
};

#endif
