#ifndef __ERRORS_H__
#define __ERRORS_H__

#include <limits.h>

enum custom_errors {
  SUCCESS = 0,
  TYPE_ERR = INT_MIN,
  COPY_ERR,
  ARGS_ERR,
  ARRAY_CREATE_PARAMS_ERR,
  READ_PARAMS_ERR,
  READ_OPEN_FILE_ERR,
  WRITE_ERR,
  WRITE_PARAMS_ERR,
  WRITE_OPEN_FILE_ERR,
  STREAM_READ_ERR,
  ALLOC_BUFFER_ERR,
  REALLOC_BUFFER_ERR,
  ALLOC_POS_ARRAY_ERR,
  ALLOC_POS_ARRAY_PARAMS_ERR,
  NAIVE_MEAN_PARAMS_ERR,
  PARALLEL_MEAN_PARAMS_ERR,
  SUM_BORDERS_ERR,
  SUM_PARAMS_ERR,
  PARALLEL_PARAMS_ERR,
  PARALLEL_PIPE_ERR,
  PARALLEL_CHILD_CREATE_ERR,
  PARALLEL_CHILD_FAILURE_ERR,
  PARALLEL_PROC_BUSY_ERR,
  PARALLEL_SHMEM_MAP_ERR,
  PARALLEL_SHMEM_UNMAP_ERR,
  PARALLEL_SEM_OPEN_ERR,
  PARALLEL_SEM_POST_ERR,
  PARALLEL_PWAIT_ERR,
};

#endif
