name: C/C++ CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gcovr
      run: sudo apt-get install python3-setuptools && sudo pip3 install git+https://github.com/gcovr/gcovr.git
    - name: Configure
      run: cd lab1 && ./configure.sh
    - name: Make
      run: cd lab1 && cd build && make
    - name: Test
      run: cd lab1 && cd build && make coverage
