name: C/C++ CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install valgrind
      run: sudo apt-get install -y valgrind
    - name: Install gcovr
      run: sudo apt-get install python3-setuptools && sudo pip3 install git+https://github.com/gcovr/gcovr.git
    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck
    - name: Run Linter
      run: cd iz2/src && cppcheck *.c
    - name: Configure
      run: cd iz2 && ./configure.sh 1
    - name: Make
      run: cd iz2 && cd build && make
    - name: Test
      run: cd iz2 && cd build && make coverage
    -name: Generate big file
      run: cd iz2/tests/stress_tests && ./generate_big_file.sh
    -name: Stress test
      run: cd iz2/tests/stress_tests && BUILD_DIR=../../build ./stress_test.sh
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: iz2/build/coverage
