name: C/C++ CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure.sh
    - name: make
      run: cd build && make
    - name: test
      run: cd build && make coverage
